Vagrant.configure("2") do |config|

  config.vm.box = "modernIE/w10-edge"
  config.vm.guest = :windows
  config.vm.boot_timeout = 100

  config.vm.network :forwarded_port, guest: 22,   host: 2222,  id: "ssh", auto_correct: true, disabled: false
  config.vm.network :forwarded_port, guest: 3389, host: 33389, id: "rdp", auto_correct: true, disabled: false
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", :auto => true
  config.vm.network :forwarded_port, guest: 5986, host: 5686

  config.vm.communicator = "winrm"

  config.ssh.username = "IEUser"
  config.ssh.password = "Passw0rd!"
  # config.ssh.port = 2222
  # config.ssh.host = "127.0.0.1"



  config.vm.provider "virtualbox" do |vm|
  vm.name = "win"
    # lets run headless
    # vm.gui = true
  end
end
