---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "hawtapp-demo"
  labels:
    project: "hawtapp-demo"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "hawtapp-demo"
  type: "LoadBalancer"
